envName: dev

default:
  app:
    destination:
      namespace: dev
      server: https://kubernetes.default.svc
    project: infra
    source:
      targetRevision: HEAD


applications: []
  # k8s-service-accounts:
  #   enabled: true
  #   enableAutoSync: true

  # service-discovery:
  #   enabled: true
  #   enableAutoSync: true

  # infra-svc:
  #   enabled: false
  #   enableAutoSync: true